// -------------------------------------------------------------
// 
// File Name: D:\Github\FlybackConverter-FPGA-based-Digital-Twin\HDL Code Generation\PID_Antiwindup\flyback_pid\PID.v
// Created: 2023-07-05 23:12:07
// 
// Generated by MATLAB 9.11 and HDL Coder 3.19
// 
// 
// -- -------------------------------------------------------------
// -- Rate and Clocking Details
// -- -------------------------------------------------------------
// Model base rate: 1e-05
// Target subsystem base rate: 1e-05
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: PID
// Source Path: flyback_pid/PID
// Hierarchy Level: 0
// 
// Simulink model description for flyback_pid:
// 
// Symmetric FIR Filter
// This example shows how to use HDL Coder(TM) to check, generate,
// and verify HDL for a fixed-point symmetric FIR filter. 
// 
// -------------------------------------------------------------

// Trial 7

`timescale 1 ns / 1 ns

module PID
          (clk,
           SP_DT,
           kp_dt,
           kp_divisor_dt,
           ki_dt,
           voltageRead,
           PV_DT,
           MV_DT,
           p_action_dt,
           i_action_dt,
           error_dt);


  input   clk;
  input   signed [15:0] SP_DT;  // int16
  input   signed [15:0] kp_dt;  // int16
  input   signed [15:0] kp_divisor_dt;  // int16
  input   signed [15:0] ki_dt;  // int16
  input   signed [15:0] voltageRead;  // int16
  output  signed [15:0] PV_DT;  // int16
  output  signed [7:0] MV_DT;  // int8
  output  signed [15:0] p_action_dt;  // int16
  output  signed [15:0] i_action_dt;  // int16
  output  signed [15:0] error_dt;  // int16


  wire signed [63:0] Add_sub_cast;  // sfix64_En32
  wire signed [63:0] Add_sub_cast_1;  // sfix64_En32
  wire signed [63:0] Add_out1;  // sfix64_En32
  wire signed [16:0] kp_dt_dtc;  // sfix17
  reg signed [15:0] SP;  // int16
  wire signed [79:0] Product_mul_temp;  // sfix80_En32
  wire signed [63:0] Product_out1;  // sfix64_En32
  wire signed [79:0] Product1_mul_temp;  // sfix80_En32
  wire signed [63:0] Product1_out1;  // sfix64_En32
  wire signed [63:0] Discrete_Time_Integrator1_indtc;  // sfix64
  wire signed [127:0] gain_mul_temp;  // sfix128_En69
  wire signed [63:0] Discrete_Time_Integrator1_u_gain;  // sfix64
  wire signed [63:0] Discrete_Time_Integrator1_u_dtc;  // sfix64_En32
  reg signed [63:0] Discrete_Time_Integrator1_x_reg;  // sfix64_En32
  wire signed [63:0] Discrete_Time_Integrator1_u_add;  // sfix64_En32
  wire signed [63:0] Add1_out1;  // sfix64_En32
  wire signed [15:0] SP_1;  // int16
  wire signed [63:0] PV;  // sfix64_En32
  wire signed [7:0] SP_2;  // int8
  wire signed [15:0] SP_3;  // int16
  wire signed [15:0] SP_4;  // int16
  wire signed [15:0] SP_5;  // int16
  reg signed [16:0] Divide_varargout_1;  // sfix17
  reg signed [17:0] Divide_div_temp;  // sfix18
  reg signed [17:0] Divide_t_0_0;  // sfix18

  initial begin
    Discrete_Time_Integrator1_x_reg = 64'sh0000000000000000;
  end

  assign Add_sub_cast = {{16{SP_DT[15]}}, {SP_DT, 32'b00000000000000000000000000000000}};
  assign Add_sub_cast_1 = {{16{voltageRead[15]}}, {voltageRead, 32'b00000000000000000000000000000000}};
  assign Add_out1 = Add_sub_cast - Add_sub_cast_1;


  assign kp_dt_dtc = {kp_dt[15], kp_dt};



  always @(kp_divisor_dt, kp_dt_dtc) begin
    Divide_div_temp = 18'sb000000000000000000;
    Divide_t_0_0 = 18'sb000000000000000000;
    if (kp_divisor_dt == 16'sb0000000000000000) begin
      if (kp_dt_dtc < 17'sb00000000000000000) begin
        Divide_varargout_1 = 17'sb10000000000000000;
      end
      else begin
        Divide_varargout_1 = 17'sb01111111111111111;
      end
    end
    else begin
      Divide_t_0_0 = {kp_dt_dtc[16], kp_dt_dtc};
      Divide_div_temp = Divide_t_0_0 / kp_divisor_dt;
      if ((Divide_div_temp[17] == 1'b0) && (Divide_div_temp[16] != 1'b0)) begin
        Divide_varargout_1 = 17'sb01111111111111111;
      end
      else if ((Divide_div_temp[17] == 1'b1) && (Divide_div_temp[16] != 1'b1)) begin
        Divide_varargout_1 = 17'sb10000000000000000;
      end
      else begin
        Divide_varargout_1 = Divide_div_temp[16:0];
      end
    end
    if ((Divide_varargout_1[16] == 1'b0) && (Divide_varargout_1[15] != 1'b0)) begin
      SP = 16'sb0111111111111111;
    end
    else if ((Divide_varargout_1[16] == 1'b1) && (Divide_varargout_1[15] != 1'b1)) begin
      SP = 16'sb1000000000000000;
    end
    else begin
      SP = Divide_varargout_1[15:0];
    end
  end


  assign Product_mul_temp = Add_out1 * SP;
  assign Product_out1 = Product_mul_temp[63:0];


  assign Product1_mul_temp = Add_out1 * ki_dt;
  assign Product1_out1 = Product1_mul_temp[63:0];


  assign Discrete_Time_Integrator1_indtc = Product1_out1;



  assign gain_mul_temp = 64'sh0014F8B588E368F1 * Discrete_Time_Integrator1_indtc;
  assign Discrete_Time_Integrator1_u_gain = {{5{gain_mul_temp[127]}}, gain_mul_temp[127:69]};



  assign Discrete_Time_Integrator1_u_dtc = Discrete_Time_Integrator1_u_gain;



  assign Discrete_Time_Integrator1_u_add = Discrete_Time_Integrator1_x_reg + Discrete_Time_Integrator1_u_dtc;



  always @(posedge clk)
    begin : Discrete_Time_Integrator1_reg_process
      Discrete_Time_Integrator1_x_reg <= Discrete_Time_Integrator1_u_add;
    end


  assign Add1_out1 = Product_out1 + Discrete_Time_Integrator1_x_reg;


  assign SP_1 = Add1_out1[47:32];


  assign PV_DT = SP_1;

  assign PV = (Add1_out1 > 64'sh000000FF00000000 ? 64'sh000000FF00000000 :
              (Add1_out1 < 64'sh0000000000000000 ? 64'sh0000000000000000 :
              Add1_out1));


  assign SP_2 = PV[39:32];


  assign MV_DT = SP_2;

  assign SP_3 = Product_out1[47:32];


  assign p_action_dt = SP_3;

  assign SP_4 = Discrete_Time_Integrator1_x_reg[47:32];


  assign i_action_dt = SP_4;

  assign SP_5 = Add_out1[47:32];


  assign error_dt = SP_5;

endmodule  // PID






